stage: test
name: snakemake
os: linux
language: python
env: MINICONDA="https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh" PYTHONVER="3.7"
install:
  - export PATH="$HOME/miniconda/bin:$PATH"
  - wget ${MINICONDA} -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - git clone https://github.com/pyiron/pyiron-resources.git resources
  - conda install -y -c conda-forge -c bioconda python=${PYTHONVER} snakemake
script:
  - snakemake --use-conda
  - mkdir public
  - cp cohesive_energy.html public/index.html
deploy:
  - provider: pages
    repo: cohesive-energy/jan-janssen.github.io
    target_branch: master
    skip_cleanup: true
    github_token: $GH_TOKEN
    local_dir: public
    on:
      branch: master
